version: 0.2

env:
  variables:
    PYLINT_THRESHOLD: "9.0"

phases:
  install:
    commands:
    - yum update -y
    - yum install -y python3-pip
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install django djangorestframework pylint
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
    - java -version
    - export JAVA_HOME=$(pwd)/sonar-scanner-5.0.1.3006-linux/jre
    - java -version
    - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
    - sonar-scanner --version

  pre_build:
    commands:
    - pip install -r requirements.txt
    - pylint --exit-zero --output-format=text busapp managements > pylint_report.txt
    - cat pylint_report.txt

  build:
    commands:
    # - python manage.py test
    # SonarQube Analysis
    # - sonar-scanner -Dsonar.projectKey=devsecopsexplore -Dsonar.organization=de3p14 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.python.pylint.reportPaths=pylint_report.txt

    - echo "build is success"
artifacts:
  files:
  - '**/*'
